CREATE UNIQUE INDEX catalog_one_active_idx ON bursar.catalog_revisions ((status)) WHERE status = 'active';
CREATE UNIQUE INDEX catalog_one_default_bucket_idx ON bursar.catalog_buckets(catalog_revision_id) WHERE is_default;
CREATE INDEX ledger_account_created_idx ON bursar.credit_ledger_entries (account_id, created_at DESC, id DESC);
CREATE INDEX ledger_reference_idx ON bursar.credit_ledger_entries (reference_entry_id) WHERE reference_entry_id IS NOT NULL;
CREATE INDEX lots_available_idx ON bursar.credit_lots (account_id, priority, expires_at, created_at, id) WHERE consumed < granted;
CREATE INDEX lot_allocations_debit_idx ON bursar.credit_lot_allocations (debit_entry_id);
CREATE INDEX usage_charge_dimensions_idx ON bursar.credit_usage_charges (created_at, operation, feature, model, region);
CREATE INDEX active_leases_idx ON bursar.credit_leases (account_id, expires_at) WHERE status = 'active';
CREATE INDEX allowance_window_lookup_idx ON bursar.allowance_windows (account_id, feature, window_start, window_end);
CREATE INDEX feature_limit_events_account_idx ON bursar.feature_limit_events (account_id, created_at DESC, id);
CREATE INDEX plan_assignments_revision_idx ON bursar.account_plan_assignments (catalog_revision_id, plan_id);
CREATE INDEX billing_events_claimable_idx ON bursar.billing_events (created_at, id) WHERE status = 'processing' OR status = 'failed';
CREATE UNIQUE INDEX open_subscription_changes_idx ON bursar.billing_subscription_changes (subscription_id) WHERE state IN ('awaiting_payment','scheduled');
CREATE INDEX active_recharge_attempts_idx ON bursar.billing_auto_recharge_attempts (subject_id, created_at DESC) WHERE state IN ('claimed','submitted','processing','unknown','action_required');
CREATE UNIQUE INDEX one_selected_entitlement_idx ON bursar.billing_entitlement_sources (subject_id) WHERE selected;
CREATE INDEX external_identities_subject_id_idx ON bursar.external_identities(subject_id);
CREATE INDEX signup_credit_grants_catalog_revision_idx ON bursar.signup_credit_grants(catalog_revision_id);
CREATE INDEX catalog_plans_included_bucket_idx ON bursar.catalog_plans(catalog_revision_id,included_credits_bucket) WHERE included_credits_bucket IS NOT NULL;
CREATE INDEX catalog_offers_plan_idx ON bursar.catalog_offers(catalog_revision_id,plan_key);
CREATE INDEX catalog_offers_grant_bucket_idx ON bursar.catalog_offers(catalog_revision_id,grant_bucket_key) WHERE grant_bucket_key IS NOT NULL;
CREATE INDEX catalog_topups_bucket_idx ON bursar.catalog_topups(catalog_revision_id,bucket_key);
CREATE INDEX catalog_auto_recharge_policies_topup_idx ON bursar.catalog_auto_recharge_policies(catalog_revision_id,topup_key);
CREATE INDEX credit_lots_catalog_bucket_idx ON bursar.credit_lots(catalog_revision_id,bucket_key);
CREATE INDEX credit_lot_allocations_lot_id_idx ON bursar.credit_lot_allocations(lot_id);
CREATE INDEX credit_usage_charges_ledger_entry_id_idx ON bursar.credit_usage_charges(ledger_entry_id) WHERE ledger_entry_id IS NOT NULL;
CREATE INDEX account_plan_assignments_plan_idx ON bursar.account_plan_assignments(plan_id,catalog_revision_id);
CREATE INDEX allowance_windows_plan_idx ON bursar.allowance_windows(plan_id,catalog_revision_id);
CREATE INDEX credit_leases_catalog_revision_id_idx ON bursar.credit_leases(catalog_revision_id);
CREATE INDEX credit_leases_ledger_entry_id_idx ON bursar.credit_leases(ledger_entry_id) WHERE ledger_entry_id IS NOT NULL;
CREATE INDEX credit_team_members_subject_id_idx ON bursar.credit_team_members(subject_id);
CREATE INDEX credit_plan_migrations_from_plan_id_idx ON bursar.credit_plan_migrations(from_plan_id) WHERE from_plan_id IS NOT NULL;
CREATE INDEX credit_plan_migrations_to_plan_id_idx ON bursar.credit_plan_migrations(to_plan_id);
CREATE INDEX billing_subscriptions_subject_id_idx ON bursar.billing_subscriptions(subject_id);
CREATE INDEX billing_subscriptions_offer_idx ON bursar.billing_subscriptions(offer_id,catalog_revision_id);
CREATE INDEX billing_entitlement_sources_subscription_idx ON bursar.billing_entitlement_sources(subscription_id,subject_id);
CREATE INDEX billing_payments_subject_id_idx ON bursar.billing_payments(subject_id);
CREATE INDEX billing_credit_grants_subject_id_idx ON bursar.billing_credit_grants(subject_id);
CREATE INDEX billing_credit_grants_payment_idx ON bursar.billing_credit_grants(payment_id,subject_id) WHERE payment_id IS NOT NULL;
CREATE INDEX billing_credit_grants_subscription_idx ON bursar.billing_credit_grants(subscription_id,subject_id) WHERE subscription_id IS NOT NULL;
CREATE INDEX billing_credit_grants_topup_idx ON bursar.billing_credit_grants(topup_id,catalog_revision_id) WHERE topup_id IS NOT NULL;
CREATE INDEX billing_credit_grants_ledger_entry_id_idx ON bursar.billing_credit_grants(ledger_entry_id) WHERE ledger_entry_id IS NOT NULL;
CREATE INDEX billing_credit_grants_event_id_idx ON bursar.billing_credit_grants(billing_event_id) WHERE billing_event_id IS NOT NULL;
CREATE UNIQUE INDEX billing_credit_grants_payment_topup_key ON bursar.billing_credit_grants(payment_id,topup_id) WHERE payment_id IS NOT NULL;
CREATE UNIQUE INDEX billing_credit_grants_event_key ON bursar.billing_credit_grants(billing_event_id) WHERE billing_event_id IS NOT NULL;
CREATE INDEX billing_refunds_payment_id_idx ON bursar.billing_refunds(payment_id);
CREATE INDEX billing_refund_grants_grant_id_idx ON bursar.billing_refund_grants(grant_id);
CREATE INDEX billing_refund_grants_ledger_entry_id_idx ON bursar.billing_refund_grants(ledger_entry_id) WHERE ledger_entry_id IS NOT NULL;
CREATE INDEX billing_subscription_changes_from_offer_id_idx ON bursar.billing_subscription_changes(from_offer_id);
CREATE INDEX billing_subscription_changes_to_offer_id_idx ON bursar.billing_subscription_changes(to_offer_id);
CREATE INDEX billing_auto_recharge_profiles_topup_id_idx ON bursar.billing_auto_recharge_profiles(topup_id) WHERE topup_id IS NOT NULL;
CREATE INDEX billing_auto_recharge_attempts_topup_id_idx ON bursar.billing_auto_recharge_attempts(topup_id);
CREATE INDEX billing_invoices_subject_id_idx ON bursar.billing_invoices(subject_id);
CREATE INDEX billing_invoices_subscription_id_idx ON bursar.billing_invoices(subscription_id) WHERE subscription_id IS NOT NULL;
CREATE INDEX billing_disputes_subject_id_idx ON bursar.billing_disputes(subject_id) WHERE subject_id IS NOT NULL;
CREATE INDEX billing_disputes_payment_id_idx ON bursar.billing_disputes(payment_id) WHERE payment_id IS NOT NULL;
