"""Optional high-volume storage infrastructure.

Importing this module requires the ``postgres`` extra, mirroring the
JavaScript SDK's Node-only storage entry point. Using the native S3 adapter
additionally requires the ``s3`` extra.
"""

from bursar.shared.postgres_client import PostgresConnectionOptions
from bursar.storage.adapters import (
    ClickHouseClient,
    ClickHouseQueryResult,
    ClickHouseUsageStore,
    ClickHouseUsageStoreOptions,
    S3BillingArchive,
    S3BillingArchiveOptions,
    S3Credentials,
    S3PutObjectOptions,
)
from bursar.storage.diagnostics import (
    BursarRuntimeDiagnostics,
    BursarRuntimeState,
    CatalogDependencyCheck,
    CheckDependenciesOptions,
    DependencyCheck,
    DependencyStatus,
    OutboxDependencyCheck,
    OutboxStatusSnapshot,
    WorkerErrorSnapshot,
    WorkerLifecycle,
    WorkerRunSnapshot,
    WorkerState,
)
from bursar.storage.maintenance import (
    BursarMaintenance,
    BursarOperatorMaintenance,
    MaintenanceOperations,
    MaintenanceRunOptions,
    MaintenanceRunResult,
    MaintenanceRunStatus,
    MaintenanceTaskResult,
    MaintenanceTaskStatus,
    OperatorMaintenanceRunOptions,
    PartitionMaintenanceResult,
    StorageMaintenanceCounts,
    StorageMaintenanceResult,
    StorageMaintenanceStatus,
    StoragePartition,
)
from bursar.storage.outbox_worker import (
    OutboxClaimLossPhase,
    OutboxEventOutcome,
    OutboxEventOutcomeStatus,
    OutboxRunResult,
    OutboxWorker,
    OutboxWorkerOptions,
)
from bursar.storage.ports import (
    BatchUsageEventSink,
    BillingEventPayloadExport,
    BillingPayloadArchive,
    BillingPayloadArchiveResult,
    OutboxClaimRenewalStore,
    OutboxDeadLetter,
    OutboxDeadLetterCursor,
    OutboxDeadLetterListOptions,
    OutboxDeadLetterPage,
    OutboxEvent,
    OutboxHandler,
    OutboxRecoveryStore,
    OutboxStats,
    OutboxStore,
    UsageChargeExport,
    UsageEventSink,
    UsageProjectionSchema,
)
from bursar.storage.runtime import (
    BursarRuntime,
    BursarRuntimeBursarOptions,
    BursarRuntimeHealth,
    BursarRuntimeOptions,
    BursarRuntimeStartOptions,
    UsageAnalyticsSink,
    create_bursar_runtime,
)

__all__ = [
    "BillingEventPayloadExport",
    "BillingPayloadArchive",
    "BillingPayloadArchiveResult",
    "BatchUsageEventSink",
    "BursarMaintenance",
    "BursarOperatorMaintenance",
    "BursarRuntime",
    "BursarRuntimeDiagnostics",
    "BursarRuntimeHealth",
    "BursarRuntimeBursarOptions",
    "BursarRuntimeOptions",
    "BursarRuntimeStartOptions",
    "BursarRuntimeState",
    "CatalogDependencyCheck",
    "CheckDependenciesOptions",
    "ClickHouseClient",
    "ClickHouseQueryResult",
    "ClickHouseUsageStore",
    "ClickHouseUsageStoreOptions",
    "DependencyCheck",
    "DependencyStatus",
    "MaintenanceRunOptions",
    "MaintenanceRunResult",
    "MaintenanceRunStatus",
    "MaintenanceOperations",
    "MaintenanceTaskResult",
    "MaintenanceTaskStatus",
    "OperatorMaintenanceRunOptions",
    "OutboxClaimLossPhase",
    "OutboxClaimRenewalStore",
    "OutboxDeadLetter",
    "OutboxDeadLetterCursor",
    "OutboxDeadLetterListOptions",
    "OutboxDeadLetterPage",
    "OutboxDependencyCheck",
    "OutboxEvent",
    "OutboxEventOutcome",
    "OutboxEventOutcomeStatus",
    "OutboxHandler",
    "OutboxRecoveryStore",
    "OutboxRunResult",
    "OutboxStats",
    "OutboxStatusSnapshot",
    "OutboxStore",
    "OutboxWorker",
    "OutboxWorkerOptions",
    "PostgresConnectionOptions",
    "PartitionMaintenanceResult",
    "S3BillingArchive",
    "S3BillingArchiveOptions",
    "S3Credentials",
    "S3PutObjectOptions",
    "StorageMaintenanceCounts",
    "StorageMaintenanceResult",
    "StorageMaintenanceStatus",
    "StoragePartition",
    "UsageAnalyticsSink",
    "UsageChargeExport",
    "UsageEventSink",
    "UsageProjectionSchema",
    "WorkerErrorSnapshot",
    "WorkerLifecycle",
    "WorkerRunSnapshot",
    "WorkerState",
    "create_bursar_runtime",
]
