"""Bursar SDK for metering, credits, subscriptions, and payments."""

from importlib import import_module
from importlib.metadata import PackageNotFoundError, version
from typing import TYPE_CHECKING

from bursar.billing.auto_recharge_service import (
    AutoRechargeProcessResult,
    AutoRechargeService,
)

try:
    __version__ = version("bursar")
except PackageNotFoundError:  # pragma: no cover - source checkout without install
    __version__ = "0.0.0+unknown"

from bursar.billing import (
    AUTO_RECHARGE_STATES,
    AllowanceGrant,
    BillingAutoRechargeAttempt,
    BillingAutoRechargeProfile,
    BillingAutoRechargeState,
    BillingAutoRechargeStatus,
    BillingCreditPostingResult,
    BillingCustomerInfo,
    BillingCustomerRecord,
    BillingDisputeInfo,
    BillingEvent,
    BillingEventClaim,
    BillingEventHandler,
    BillingEventResult,
    BillingEventType,
    BillingInvoiceInfo,
    BillingInvoiceRecord,
    BillingOfferInterval,
    BillingPaymentInfo,
    BillingPaymentRecord,
    BillingPreferences,
    BillingProvider,
    BillingRefundInfo,
    BillingStore,
    BillingSubscriptionChange,
    BillingSubscriptionChangeInput,
    BillingSubscriptionChangeState,
    BillingSubscriptionInfo,
    BillingSubscriptionOfferContext,
    BillingSubscriptionProrationBehavior,
    BillingSubscriptionState,
    BillingSubscriptionStatus,
    CycleGrant,
    EntitlementMode,
    ProviderRef,
    SubscriptionGrant,
)
from bursar.billing.billing_service import BillingProvisioningPort
from bursar.billing.service_types import BillingServiceOptions
from bursar.breakdown import CostBreakdown, make_cost_breakdown
from bursar.bursar import (
    AccountCreatedResult,
    AccountService,
    BillingCapability,
    BillingEventSink,
    Bursar,
    CatalogService,
)
from bursar.catalog import (
    PublicCatalog,
    PublicCatalogAllowance,
    PublicCatalogDisplay,
    PublicCatalogInterval,
    PublicCatalogOffer,
    PublicCatalogPlan,
    PublicCatalogPrice,
    PublicCatalogQuantity,
    PublicCatalogQuota,
    PublicCatalogWindow,
    project_public_catalog,
)
from bursar.commerce import (
    AccountAllowanceOverview,
    AccountCommerceOverview,
    AccountCreditOverview,
    AccountSubscriptionSummary,
    ActiveSubscriptionError,
    AutoRechargeInput,
    AutoRechargeProcessResultLike,
    BillingDocumentInvoiceLocator,
    BillingDocumentInvoiceRef,
    BillingDocumentLedgerLocator,
    BillingDocumentLedgerRef,
    BillingDocumentLocator,
    BillingDocumentRef,
    CancelAllSubscriptionsResult,
    CancelSubscriptionResult,
    CheckoutCompletedError,
    CheckoutConflictError,
    CheckoutStatusResult,
    CommerceAutoRecharge,
    CommerceCheckoutKind,
    CommerceCheckoutStatus,
    CommerceError,
    CommerceNotConfiguredError,
    CommerceOptions,
    CommercePreferenceDefaults,
    CommerceProviderFactory,
    CommerceProviderFactoryContext,
    CommerceProviderRegistry,
    CommerceResourceNotFoundError,
    CommerceSectionAvailability,
    CommerceService,
    CommerceWebhookInput,
    CommerceWebhookResult,
    ConfirmPlanChangeInput,
    ConfirmPlanChangeResult,
    CoreBillingDataUnavailableError,
    CreateCheckoutInput,
    CreateCheckoutResult,
    CreditSpendSource,
    GetInvoiceLinkInput,
    InvalidOfferQuantityError,
    MissingPlanChangePolicyError,
    NormalizedPendingPlanChange,
    PlanChangeClassification,
    PlanChangePreviewResult,
    PortalSessionInput,
    PreferencePatch,
    PreviewPlanChangeInput,
    ProviderSelectionError,
    QuoteChangedError,
    SubscriptionCommandResult,
    UnknownOfferError,
)

if TYPE_CHECKING:
    from bursar.billing import PostgresBillingStore
    from bursar.credits.postgres.store import PostgresStore
    from bursar.shared.postgres_client import PostgresConnectionOptions
from bursar.config import (
    BursarConfig,
    BursarConfigData,
    CatalogRollout,
    Charge,
    CommerceConfig,
    ConfigError,
    CreditsConfig,
    FeatureDefinition,
    ParsedBursarConfig,
    PlanDefinition,
    PlanEvolution,
    PlanRollout,
    PlanRolloutStrategy,
    PricingConfig,
    Window,
    canonical_bursar_config_dict,
    canonical_catalog_rollout_dict,
    load_catalog_rollout,
    load_config_from_dict,
    validate_catalog_rollout,
)
from bursar.credits.events import CreditEvent, CreditEventEmitter
from bursar.credits.service import (
    CatalogNotLoadedError,
    ConcurrencyLimitError,
    CreditError,
    CreditsService,
    FeatureNotEntitledError,
    InsufficientCreditsError,
    LeaseExpiredError,
    LeaseNotFoundError,
    OperationNotAllowedError,
    QuotaExceededError,
)
from bursar.credits.service_types import (
    BeginBilledOperationOptions,
    CanAffordOptions,
    CreditsServiceOptions,
    GrantSubscriptionCycleOptions,
    LowBalanceConfig,
    MetricsOrAmount,
    PostDeductionContext,
    ReserveOptions,
    RunBilledAsyncOptions,
    RunBilledOptions,
    SettleOptions,
)
from bursar.credits.store import (
    CapabilityNotSupportedError,
    CapReachedError,
    CreateLeaseOptions,
    CreditStore,
    RefundError,
    SettleLeaseOptions,
    StoreError,
)
from bursar.credits.types import (
    AddCreditsResult,
    AddTeamMemberResult,
    AggregateStats,
    AllowanceResult,
    AvailableResult,
    BalanceResult,
    BucketBalance,
    BucketBalancesResult,
    BucketDefinition,
    CanAffordResult,
    CatalogRevision,
    CatalogRevisionSummary,
    CheckFeatureResult,
    CreateTeamResult,
    CreditMetadata,
    DailySpendRow,
    DeductionResult,
    DeductWithAllowanceOptions,
    ExecuteGrantProgramRequest,
    GetUserPlanResult,
    GrantProgramAwardResult,
    GrantProgramTrigger,
    LeasePricingContext,
    LeaseResult,
    LedgerCursor,
    LedgerEntry,
    LedgerPage,
    ListLedgerEntriesOptions,
    ListQuotaEventsOptions,
    ListUsageChargesOptions,
    ListUsageEntriesOptions,
    OperationPolicy,
    PlanAdmissionPolicy,
    PlanAllowancePolicy,
    PlanCreditPolicy,
    PlanMigrationBatchResult,
    PlanMigrationStartResult,
    QuotaEvent,
    QuotaState,
    RefundResult,
    ReleaseResult,
    SetUserPlanResult,
    SpendByModelRow,
    SpendByUserRow,
    SweepResult,
    Team,
    TeamBalanceResult,
    TeamDeductionResult,
    TeamMember,
    TopUserRow,
    UsageAnalyticsStore,
    UsageCharge,
    UsageChargeCursor,
    UsageChargePage,
    UsageRecordResult,
)
from bursar.engine import PricingEngine
from bursar.errors import (
    AutoRechargeDisabledError,
    AutoRechargeNotConfiguredError,
    BillingError,
    BursarError,
    BursarErrorCategory,
    BursarImportError,
    CapabilityNotConfiguredError,
    PaymentMethodRequiredError,
    ProviderCapabilityNotSupportedError,
    StoreClosedError,
    StoreTimeoutError,
    StoreUnavailableError,
    bursar_error_http_status,
    bursar_error_public_message,
    is_bursar_error,
    is_retryable_bursar_error,
)
from bursar.expr import ExpressionError, evaluate_expression, quantize_money, validate_expression
from bursar.load_config_file import load_config_file
from bursar.metrics import UsageMetrics
from bursar.providers.types import (
    CheckoutParams,
    CreateCustomerParams,
    PaymentMethodInfo,
    PaymentMethodSetupParams,
    PaymentProvider,
    PortalParams,
    ProviderLogger,
    UpdatePaymentMethodParams,
    WebhookRequest,
)
from bursar.retry import (
    BursarRetryOptions,
    retry_bursar_operation,
    retry_bursar_operation_async,
)

_LAZY_EXPORTS = {
    "PostgresBillingStore": ("bursar.billing", "PostgresBillingStore"),
    "PostgresStore": ("bursar.credits.postgres.store", "PostgresStore"),
    "PostgresConnectionOptions": ("bursar.shared.postgres_client", "PostgresConnectionOptions"),
}


def __getattr__(name: str) -> object:
    """Lazy-import Postgres stores — they require the optional psycopg2 extra."""
    target = _LAZY_EXPORTS.get(name)
    if target is not None:
        module_name, attribute_name = target
        value = getattr(import_module(module_name), attribute_name)
        globals()[name] = value
        return value
    msg = f"module {__name__!r} has no attribute {name!r}"
    raise AttributeError(msg)


__all__ = [
    "AccountCreatedResult",
    "BillingAutoRechargeAttempt",
    "BillingAutoRechargeProfile",
    "BillingAutoRechargeStatus",
    "BillingAutoRechargeState",
    "AUTO_RECHARGE_STATES",
    "AutoRechargeProcessResult",
    "AutoRechargeService",
    "AddCreditsResult",
    "AddTeamMemberResult",
    "AggregateStats",
    "AccountAllowanceOverview",
    "AccountCreditOverview",
    "AccountSubscriptionSummary",
    "AllowanceGrant",
    "AllowanceResult",
    "AvailableResult",
    "BalanceResult",
    "BillingCreditPostingResult",
    "BillingCustomerInfo",
    "BillingCustomerRecord",
    "BillingDisputeInfo",
    "BillingEvent",
    "BillingEventClaim",
    "BillingEventHandler",
    "BillingEventResult",
    "BillingEventType",
    "BillingInvoiceInfo",
    "BillingInvoiceRecord",
    "BillingOfferInterval",
    "BillingPaymentInfo",
    "BillingPaymentRecord",
    "BillingPreferences",
    "BillingProvider",
    "BillingRefundInfo",
    "BillingStore",
    "BillingProvisioningPort",
    "BillingServiceOptions",
    "BillingError",
    "AutoRechargeDisabledError",
    "AutoRechargeNotConfiguredError",
    "Bursar",
    "BursarError",
    "BursarErrorCategory",
    "BursarImportError",
    "StoreClosedError",
    "StoreTimeoutError",
    "StoreUnavailableError",
    "bursar_error_http_status",
    "bursar_error_public_message",
    "is_bursar_error",
    "is_retryable_bursar_error",
    "BursarRetryOptions",
    "retry_bursar_operation",
    "retry_bursar_operation_async",
    "BillingEventSink",
    "BillingCapability",
    "CatalogService",
    "CommerceService",
    "CommerceAutoRecharge",
    "CommerceCheckoutKind",
    "CommerceCheckoutStatus",
    "CommerceOptions",
    "CommercePreferenceDefaults",
    "CommerceProviderFactory",
    "CommerceProviderFactoryContext",
    "CommerceProviderRegistry",
    "CommerceError",
    "CommerceNotConfiguredError",
    "UnknownOfferError",
    "InvalidOfferQuantityError",
    "ActiveSubscriptionError",
    "CheckoutConflictError",
    "CheckoutCompletedError",
    "CommerceResourceNotFoundError",
    "ProviderSelectionError",
    "ProviderCapabilityNotSupportedError",
    "QuoteChangedError",
    "MissingPlanChangePolicyError",
    "PaymentMethodRequiredError",
    "CoreBillingDataUnavailableError",
    "CreditSpendSource",
    "AccountCommerceOverview",
    "AccountService",
    "PublicCatalog",
    "PublicCatalogAllowance",
    "PublicCatalogDisplay",
    "PublicCatalogInterval",
    "PublicCatalogOffer",
    "PublicCatalogPlan",
    "PublicCatalogPrice",
    "PublicCatalogQuantity",
    "PublicCatalogQuota",
    "PublicCatalogWindow",
    "AutoRechargeInput",
    "AutoRechargeProcessResultLike",
    "BillingDocumentInvoiceLocator",
    "BillingDocumentInvoiceRef",
    "BillingDocumentLedgerLocator",
    "BillingDocumentLedgerRef",
    "BillingDocumentLocator",
    "BillingDocumentRef",
    "CheckoutStatusResult",
    "CancelAllSubscriptionsResult",
    "CancelSubscriptionResult",
    "CommerceSectionAvailability",
    "CommerceWebhookInput",
    "CommerceWebhookResult",
    "ConfirmPlanChangeInput",
    "ConfirmPlanChangeResult",
    "CreateCheckoutInput",
    "CreateCheckoutResult",
    "GetInvoiceLinkInput",
    "PlanChangeClassification",
    "PlanChangePreviewResult",
    "NormalizedPendingPlanChange",
    "PortalSessionInput",
    "PreferencePatch",
    "PreviewPlanChangeInput",
    "SubscriptionCommandResult",
    "BillingSubscriptionChange",
    "BillingSubscriptionChangeInput",
    "BillingSubscriptionChangeState",
    "BillingSubscriptionInfo",
    "BillingSubscriptionOfferContext",
    "BillingSubscriptionProrationBehavior",
    "BillingSubscriptionState",
    "BillingSubscriptionStatus",
    "BucketBalance",
    "BucketBalancesResult",
    "BucketDefinition",
    "CanAffordResult",
    "CapReachedError",
    "CapabilityNotConfiguredError",
    "CapabilityNotSupportedError",
    "CheckFeatureResult",
    "CheckoutParams",
    "ConcurrencyLimitError",
    "ConfigError",
    "CostBreakdown",
    "CreditsService",
    "CreditsServiceOptions",
    "BeginBilledOperationOptions",
    "CanAffordOptions",
    "GrantSubscriptionCycleOptions",
    "LowBalanceConfig",
    "MetricsOrAmount",
    "PostDeductionContext",
    "ReserveOptions",
    "RunBilledAsyncOptions",
    "RunBilledOptions",
    "SettleOptions",
    "CreateCustomerParams",
    "CreateLeaseOptions",
    "CreateTeamResult",
    "CreditError",
    "CreditStore",
    "CreditEvent",
    "CreditEventEmitter",
    "CreditMetadata",
    "CycleGrant",
    "EntitlementMode",
    "DailySpendRow",
    "DeductWithAllowanceOptions",
    "DeductionResult",
    "ExecuteGrantProgramRequest",
    "evaluate_expression",
    "ExpressionError",
    "FeatureNotEntitledError",
    "GetUserPlanResult",
    "GrantProgramAwardResult",
    "GrantProgramTrigger",
    "InsufficientCreditsError",
    "LeaseExpiredError",
    "LeaseNotFoundError",
    "LeasePricingContext",
    "LeaseResult",
    "LedgerCursor",
    "LedgerEntry",
    "LedgerPage",
    "ListLedgerEntriesOptions",
    "ListQuotaEventsOptions",
    "ListUsageChargesOptions",
    "ListUsageEntriesOptions",
    "make_cost_breakdown",
    "load_catalog_rollout",
    "load_config_file",
    "validate_catalog_rollout",
    "OperationNotAllowedError",
    "OperationPolicy",
    "PlanAdmissionPolicy",
    "PlanAllowancePolicy",
    "PlanCreditPolicy",
    "PlanMigrationBatchResult",
    "PlanMigrationStartResult",
    "PaymentMethodInfo",
    "PaymentMethodSetupParams",
    "PaymentProvider",
    "PlanDefinition",
    "PlanEvolution",
    "PlanRollout",
    "PlanRolloutStrategy",
    "PortalParams",
    "PostgresBillingStore",
    "PostgresStore",
    "PostgresConnectionOptions",
    "BursarConfig",
    "CatalogRevision",
    "CatalogRevisionSummary",
    "CatalogRollout",
    "canonical_catalog_rollout_dict",
    "PricingEngine",
    "CatalogNotLoadedError",
    "quantize_money",
    "QuotaEvent",
    "QuotaExceededError",
    "QuotaState",
    "ProviderLogger",
    "ProviderRef",
    "SubscriptionGrant",
    "RefundError",
    "RefundResult",
    "ReleaseResult",
    "SetUserPlanResult",
    "SettleLeaseOptions",
    "SpendByModelRow",
    "SpendByUserRow",
    "StoreError",
    "SweepResult",
    "Team",
    "TeamBalanceResult",
    "TeamDeductionResult",
    "TeamMember",
    "TopUserRow",
    "UsageAnalyticsStore",
    "UsageCharge",
    "UsageChargeCursor",
    "UsageChargePage",
    "UsageRecordResult",
    "UpdatePaymentMethodParams",
    "UsageMetrics",
    "validate_expression",
    "WebhookRequest",
    "BursarConfigData",
    "Charge",
    "CommerceConfig",
    "CreditsConfig",
    "FeatureDefinition",
    "ParsedBursarConfig",
    "PricingConfig",
    "Window",
    "canonical_bursar_config_dict",
    "load_config_from_dict",
    "project_public_catalog",
]
