#!/usr/bin/env bash
set -euo pipefail

BURSAR_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"
SQL_DIR="$BURSAR_ROOT/python/src/bursar/sql"
OUTPUT="$BURSAR_ROOT/docs/docs/concepts/database-schema.md"
TEMP_DIR="$(mktemp -d)"
SCHEMA_FILE="$TEMP_DIR/bursar-schema.sql"
MERMAID_FILE="$TEMP_DIR/bursar-schema.mmd"

trap 'rm -rf "$TEMP_DIR"' EXIT

# db-schema-toolkit accepts one schema file; concatenate the ordered migrations
# without interpreting or rewriting the SQL.
awk 'FNR == 1 && NR != 1 { print "" } { print }' "$SQL_DIR"/*.sql > "$SCHEMA_FILE"

npx --no-install db-schema-toolkit export \
  "$SCHEMA_FILE" \
  --format mermaid \
  --output "$MERMAID_FILE" \
  --db-type postgresql

{
  cat <<'EOF'
---
title: Database schema
description: Generated ERD for Bursar's PostgreSQL schema.
---

<!-- Generated by db-schema-toolkit; do not edit manually. -->

# Database schema

This diagram is generated from the canonical SQL migrations in
`python/src/bursar/sql/`.

```mermaid
EOF
  cat "$MERMAID_FILE"
  printf '\n```\n'
} > "$OUTPUT"

echo "Wrote $OUTPUT"
