import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

const sidebars: SidebarsConfig = {
  docs: [
    'intro',
    'quickstart',
    {
      type: 'category',
      label: 'Core concepts',
      link: {type: 'generated-index'},
      items: [
        'concepts/data-model',
        'concepts/configuration',
        'concepts/pricing',
        'concepts/expressions',
        'concepts/plans',
        'concepts/billing',
        'concepts/architecture',
      ],
    },
    {
      type: 'category',
      label: 'Guides',
      link: {type: 'generated-index'},
      items: [
        'guides/credit-lifecycle',
        'guides/financial-safety',
        'guides/multitenancy',
        'guides/subscription-integration',
        'guides/storage-backends',
      ],
    },
    'cli',
    {
      type: 'category',
      label: 'API reference',
      link: {type: 'generated-index', slug: 'api'},
      items: [
        {
          type: 'category',
          label: 'Python API',
          link: {type: 'doc', id: 'python-api/index'},
          items: [
            'python-api/pricing-engine',
            'python-api/credit-manager',
            'python-api/stores',
            {
              type: 'category',
              label: 'Reference',
              link: {type: 'generated-index', slug: 'python-api/reference'},
              items: [{type: 'autogenerated', dirName: 'python-api/reference'}],
            },
          ],
        },
        {
          type: 'category',
          label: 'JavaScript API',
          link: {type: 'doc', id: 'javascript-api/index'},
          items: [
            'javascript-api/pricing-engine',
            'javascript-api/credit-manager',
            'javascript-api/stores',
            {
              type: 'category',
              label: 'Reference',
              link: {type: 'generated-index', slug: 'javascript-api/reference'},
              items: [{type: 'autogenerated', dirName: 'javascript-api/reference'}],
            },
          ],
        },
      ],
    },
    {
      type: 'category',
      label: 'Notebooks',
      link: {type: 'generated-index', slug: 'notebooks'},
      items: [
        'notebooks/why_bursar_and_setup',
        'notebooks/first_pricing_config',
        'notebooks/pricing_engine',
        'notebooks/expression_language',
        'notebooks/credit_lifecycle',
        'notebooks/plans_and_allowances',
        'notebooks/quotas_and_spend_caps',
        'notebooks/credit_tiers_and_expiry',
        'notebooks/leases_and_financial_safety',
        'notebooks/teams',
        'notebooks/analytics',
        'notebooks/events',
        'notebooks/subscriptions_and_auto_recharge',
        'notebooks/cli_and_deployment',
        'notebooks/custom_stores',
        'notebooks/pricing_config_schema',
      ],
    },
  ],
};

export default sidebars;
