import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

const sidebars: SidebarsConfig = {
  docs: [
    'intro',
    {
      type: 'category',
      label: 'Python API',
      link: {type: 'doc', id: 'python-api/index'},
      items: [
        'python-api/pricing-engine',
        'python-api/credit-manager',
        'python-api/stores',
        {
          type: 'category',
          label: 'Reference',
          link: {type: 'generated-index', slug: 'python-api/reference'},
          items: [{type: 'autogenerated', dirName: 'python-api/reference'}],
        },
      ],
    },
    {
      type: 'category',
      label: 'JavaScript API',
      link: {type: 'doc', id: 'javascript-api/index'},
      items: [
        'javascript-api/pricing-engine',
        'javascript-api/credit-manager',
        'javascript-api/stores',
        {
          type: 'category',
          label: 'Reference',
          link: {type: 'generated-index', slug: 'javascript-api/reference'},
          items: [{type: 'autogenerated', dirName: 'javascript-api/reference'}],
        },
      ],
    },
    'expressions',
    'configuration',
    'financial-safety',
    'storage-backends',
    'cli',
    'architecture',
    {
      type: 'category',
      label: 'Notebooks',
      link: {type: 'generated-index', slug: 'notebooks'},
      items: [
        'notebooks/concepts_and_setup',
        'notebooks/pricing_basics',
        'notebooks/expression_language',
        'notebooks/credit_lifecycle',
        'notebooks/plans_and_allowances',
        'notebooks/credit_expiry',
        'notebooks/financial_safety',
        'notebooks/spend_caps',
        'notebooks/teams',
        'notebooks/analytics',
        'notebooks/events',
        'notebooks/custom_store',
        'notebooks/cli_and_deployment',
        'notebooks/credit_tiers',
      ],
    },
  ],
};


export default sidebars;
